const returnMimeType = (mimeType) => {
  switch (mimeType) {
    case "image/jpeg":
      return 1;
    case "image/apng":
      return 2;
    case "image/avif":
      return 3;
    case "image/gif":
      return 4;
    case "image/svg+xml":
      return 5;
    case "image/bmp":
      return 6;
    case "image/webp":
      return 7;
    case "image/png":
      return 8;
    case "image/vnd.microsoft.icon":
      return 9;
    case "audio/aac":
      return 10;
    case "audio/wav":
      return 11;
    case "audio/mpeg":
      return 12;
    case "application/x-abiword":
      return 13;
    case "application/x-httpd-php":
      return 14;
    case "application/x-freearc":
      return 15;
    case "application/vnd.amazon.ebook":
      return 16;
    case "application/octet-stream":
      return 17;
    case "application/x-bzip":
      return 18;
    case "application/x-bzip2":
      return 19;
    case "application/vnd.ms-powerpoint":
      return 20;
    case "application/x-cdf":
      return 21;
    case "application/x-csh":
      return 22;
    case "application/msword":
      return 23;
    case "application/vnd.ms-fontobject":
      return 24;
    case "application/gzip":
      return 25;
    case "application/vnd.rar":
      return 26;
    case "application/rtf":
      return 27;
    case "application/json":
      return 28;
    case "application/ld+json":
      return 29;
    case "application/x-tar":
      return 30;
    case "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
      return 31;
    case "application/vnd.openxmlformats-officedocument.presentationml.presentation":
      return 32;
    case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
      return 33;
    case "application/xml":
      return 34;
    case "application/zip":
      return 35;
    case "application/x-7z-compressed":
      return 36;
    case "application/pdf":
      return 37;
    case "application/vnd.ms-excel":
      return 38;
    case "application/java-archive":
      return 39;
    case "text/css":
      return 40;
    case "text/csv":
      return 41;
    case "text/plain":
      return 42;
    case "text/html":
      return 43;
    case "text/x-python":
      return 44;
    case "text/calendar":
      return 45;
    case "text/javascript":
      return 46;
    case "video/x-msvideo":
      return 47;
    case "video/mp4":
      return 48;
    case "video/mpeg":
      return 49;
    case "application/x-zip-compressed":
      return 50;
    default:
      return 1;
  }
};

module.exports = {
  returnMimeType,
};
