const mimeTypes = {
  "image/jpeg": 1,
  "image/apng": 2,
  "image/avif": 3,
  "image/gif": 4,
  "image/svg+xml": 5,
  "image/bmp": 6,
  "image/webp": 7,
  "image/png": 8,
  "image/vnd.microsoft.icon": 9,
  "audio/aac": 10,
  "audio/wav": 11,
  "audio/mpeg": 12,
  "application/x-abiword": 13,
  "application/x-httpd-php": 14,
  "application/x-freearc": 15,
  "application/vnd.amazon.ebook": 16,
  "application/octet-stream": 17,
  "application/x-bzip": 18,
  "application/x-bzip2": 19,
  "application/vnd.ms-powerpoint": 20,
  "application/x-cdf": 21,
  "application/x-csh": 22,
  "application/msword": 23,
  "application/vnd.ms-fontobject": 24,
  "application/gzip": 25,
  "application/vnd.rar": 26,
  "application/rtf": 27,
  "application/json": 28,
  "application/ld+json": 29,
  "application/x-tar": 30,
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": 31,
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": 32,
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": 33,
  "application/xml": 34,
  "application/zip": 35,
  "application/x-7z-compressed": 36,
  "application/pdf": 37,
  "application/vnd.ms-excel": 38,
  "application/java-archive": 39,
  "text/css": 40,
  "text/csv": 41,
  "text/plain": 42,
  "text/html": 43,
  "text/x-python": 44,
  "text/calendar": 45,
  "text/javascript": 46,
  "video/x-msvideo": 47,
  "video/mp4": 48,
  "video/mpeg": 49,
  "application/x-zip-compressed": 50,
};

module.exports = {
  mimeTypes,
};
