export const VERIFY_TOKEN_STARTED = 'VERIFY_TOKEN_STARTED';
export const VERIFY_TOKEN_END = 'VERIFY_TOKEN_END';
 
export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
 
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_UPDATE_CHAT = 'USER_UPDATE_CHAT'
export const USER_SET_NEW_PERSON_CONVERSATION = 'USER_SET_NEW_PERSON_CONVERSATION'
export const USER_SET_SEARCH_BOX_CONTENT = 'USER_SET_SEARCH_BOX_CONTENT'
export const USER_RESET_SEARCH_BOX_CONTENT = 'USER_RESET_SEARCH_BOX_CONTENT'
export const USER_SET_PERSON_SEARCH_LIST = 'USER_SET_PERSON_SEARCH_LIST'
export const USER_RESET_PERSON_SEARCH_LIST = 'USER_RESET_PERSON_SEARCH_LIST'

export const USER_SET_ROOM_LIST = 'USER_SET_ROOM_LIST'
export const USER_RESET_ROOM_LIST = 'USER_RESET_ROOM_LIST'
export const RESET_NEW_ROOM_ITEMS = 'RESET_NEW_ROOM_ITEMS'
export const USER_UPDATE_ROOM_MESSAGES = 'USER_UPDATE_ROOM_MESSAGES'
export const USER_ADD_NEW_MESSAGE = 'USER_ADD_NEW_MESSAGE'
export const UPDATE_FILE_DELTA = 'UPDATE_FILE_DELTA'
export const UPDATE_ADD_USER_IN_GROUP = 'UPDATE_ADD_USER_IN_GROUP'